plans:
  - url: https://stundenplan.ostfalia.de/b/wp/index.html
    faculty: Bau-Wasser-Boden
    graphical: true
  - url: https://stundenplan.ostfalia.de/e/
    faculty: Elektrotechnik
    graphical: true
  - url: https://stundenplan.ostfalia.de/f/wp/index.html
    faculty: Fahrzeugtechnik
    graphical: true
  - url: https://stundenplan.ostfalia.de/g/wp/index.html
    faculty: Gesundheitswesen
    graphical: true
  - url: https://stundenplan.ostfalia.de/h/wp/index.html
    faculty: Handel und Soziale Arbeit
    graphical: true
  - url: https://stundenplan.ostfalia.de/i/Semester/Semester-Liste/
    faculty: Informatik
    graphical: false
#  - url: https://www.ostfalia.de/cms/de/k/studium/stundenplaene/wintersemester/wochenplaene/
#    faculty: Verkehr-Sport-Tourismus-Medien
#    graphical: true
  - url: https://stundenplan.ostfalia.de/m/sem/index.html
    faculty: Maschinenbau
    graphical: true
  - url: https://stundenplan.ostfalia.de/r/studentenset/index.html
    faculty: Recht / BELS
    graphical: true
  - url: https://stundenplan.ostfalia.de/s/wp/index.html
    faculty: Soziale Arbeit
    graphical: false
#  - url: https://stundenplan.ostfalia.de/v/stundenplan/wing/index.html
#    faculty: Versorgungstechnik
#    graphical: true
  - url: https://stundenplan.ostfalia.de/w/wp/index.html
    faculty: Wirtschaft
    graphical: true


general:
  base_url: https://stundenplan.ostfalia.de
