current_sem: "ss23"
# timetables with the following strings in the URL or description will be filtered out (use lowercase only)
timetable_blacklist:
  - "ws2022"
  - "ws 22"
  - "wise"
  - "/ws/"
  - "pruefung"
  - "klausur"
  - "pr체fung"

plans:
  # Pl채ne sind woanders abgelegt (nicht unter stundenplan.ostfalia.de), geht nicht
  # - url: https://www.ostfalia.de/cms/de/b/studium/stundenplaene/
  #   faculty: Bau-Wasser-Boden
  - url: https://stundenplan.ostfalia.de/e/
    faculty: Elektrotechnik
  # Pl채ne sind zwar online, aber Formatierung mit der Uhrzeit mittendrin ist zu kompliziert
  # - url: https://stundenplan.ostfalia.de/f/wp/index.html
  #   faculty: Fahrzeugtechnik
  - url: https://stundenplan.ostfalia.de/g/wp/index.html
    faculty: Gesundheitswesen
    shorthand_syntax: True
  - url: https://stundenplan.ostfalia.de/h/wp/index.html
    faculty: Handel und Soziale Arbeit
  - url: https://stundenplan.ostfalia.de/i/Alle%20Daten%20im%20CSV-Format/Semester/
    faculty: Informatik
    type: "csv"
  - url: https://stundenplan.ostfalia.de/k/prod/vorlesungsplaene/wp/ss/
    faculty: Verkehr-Sport-Tourismus-Medien
  # Die Timetables haben keine Uhrzeit in den einzelnen Elementen => zu hart f체r SplusEins
  # - url: https://stundenplan.ostfalia.de/m/sem/index.html
  #  faculty: Maschinenbau
  - url: https://stundenplan.ostfalia.de/r/studentenset/index.html
    faculty: Recht
  - url: https://stundenplan.ostfalia.de/s/wp/index.html
    faculty: Soziale Arbeit
  - url: https://stundenplan.ostfalia.de/v/stundenplan/bee/
    faculty: Versorgungstechnik
    shorthand_syntax: True
  - url: https://stundenplan.ostfalia.de/v/stundenplan/egt/
    faculty: Versorgungstechnik
    shorthand_syntax: True
  - url: https://stundenplan.ostfalia.de/v/stundenplan/wing/
    faculty: Versorgungstechnik
    shorthand_syntax: True
  - url: https://stundenplan.ostfalia.de/v/stundenplan/dt/
    faculty: Versorgungstechnik
    shorthand_syntax: True
  - url: https://stundenplan.ostfalia.de/v/stundenplan/ge/
    faculty: Versorgungstechnik
    shorthand_syntax: True
  - url: https://stundenplan.ostfalia.de/v/stundenplan/sce/
    faculty: Versorgungstechnik
    shorthand_syntax: True
  # Haben exakt einen einzigen Stundenplan:
  # - url: https://stundenplan.ostfalia.de/w/wp/index.html
  #   faculty: Wirtschaft
